server:
  port: 9527

spring:
  application:
    name: cloud-gateway
    #############################新增网关配置###########################
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
           # - After=2021-11-14T11:10:43.443+08:00[Asia/Shanghai]
           # - Cookie=username,yuzy # curl http://localhost:9527/payment/lb --cookie "username=yuzy"
            - Header=X-Request-Id, \d+ # 请求头要有X-Request-Id属性，并且值为整数的正则表达式
            - Method=GET #get请求
            - Query=username, \d+ #要有参数名username并且值为整数才能路由
  ####################################################################
eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
